#!/bin/sh

PLAYER_GRAPH="^r3,1,6,6^^r0,7,12,8^^r3,15,6,8^^c#ac7e04^^r2,7,1,8^^r9,7,1,8^^r3,7,6,1^^r3,15,6,1^^r3,21,6,1^^r4,4,1,1^^r7,4,1,1^^r3,1,6,1^^r3,2,1,1^^r8,2,1,1^^f12^^d^"

ping -n -c 1 -W 0.1 8.8.8.8 &> /dev/null
[ $? -ne 0 ] && exit 1

for player in $( timeout 10 ssh farpoint.v2 ./listonlineplayers.sh ); do
	echo "$PLAYER_GRAPH $player "
done

echo " "
