#!/bin/sh
period=3

SEVSEG="$HOME/.local/bin/scripts/seven_seg"

WIFI_GRAPH='^a0,2,16,16,50,80^^a2,5,12,12,55,70^^a7,8,2,2,0,360^'
BLUE_GRAPH='^l8,13,8,22^^l9,13,12,16^^l11,15,9,17^^l9,17,12,20^^l11,19,9,21^^l8,17,5,20^^l8,17,5,15^'

# CHECK IF CONNECTED TO THE INTERNET
ping -n -c 1 -W 0.1 8.8.8.8 &> /dev/null
if [ $? -eq 0 ]; then
	WIFI_STAT='^c#00bb00^^r0,3,5,6^^d^'
else
	WIFI_STAT='^c#ff0000^^r0,3,5,6^^d^'
fi

# UPDATES TRAFFIC THROUGHPUT
netlog="$HOME/.cache/netlog"
[ -f $netlog ] || touch $netlog

prevdata=$( cat $netlog )
rxcur=$( cat /sys/class/net/wlp2s0/statistics/rx_bytes )
txcur=$( cat /sys/class/net/wlp2s0/statistics/tx_bytes )
if [ "$prevdata" != "" ] && [ "$prevdata" != " " ]; then

	delta_rx=$(( ($rxcur-${prevdata%% *}) / 1024))
	delta_tx=$(( ($txcur-${prevdata##* }) / 1024))

	rx="^l0,4,3,7^^l3,6,6,3^^l0,5,3,8^^l3,7,6,4^^f$(( 28 - (4 * ${#delta_rx} )))^$( $SEVSEG $delta_rx 3 0 3 )^f2^"
	tx="^l0,6,3,3^^l3,4,6,7^^l0,7,3,4^^l3,5,6,8^^f$(( 28 - (4 * ${#delta_tx} )))^$( $SEVSEG $delta_tx 3 0 3 )^f2^"
	KiB="^c#c07202^^r0,3,1,7^^l1,6,4,2^^l2,6,3,10^^r6,4,1,1^^r6,6,1,4^^r9,2,1,8^^a6,2,6,3,-90,180^^a6,6,6,3,-90,180^^f15^^d^"
	WIFI_RXTX="$rx$KiB^f4^$tx$KiB"
fi

# Comment this line to display cummulative consumption
echo "$rxcur $txcur" > "$netlog"

# 
which bluetoothctl 2>&1 > /dev/null
if [ "$?" -eq "0" ]; then
	blue_data=$( timeout 0.1 bluetoothctl show )
	if [ $? -eq 124 ]; then
		BLUE_STAT='^c#06060a^^r0,15,20,6^^d^'
	else
		[ "$( echo $blue_data | cut -d ' ' -f 11 )" == "yes" ] && BLUE_STAT='^c#00bb00^' || BLUE_STAT='^c#aa0000^'
		BLUE_STAT=$BLUE_STAT'^r0,15,29,4^^d^'
		[ "$( echo $blue_data | cut -d ' ' -f 13 )" == "yes" ] && BLUE_STAT=$BLUE_STAT'^c#00bb00^' || BLUE_STAT=$BLUE_STAT'^c#aa0000^'
		BLUE_STAT=$BLUE_STAT'^r32,15,29,4^^d^'
		[ "$( echo $blue_data | cut -d ' ' -f 17 )" == "yes" ] && BLUE_STAT=$BLUE_STAT'^c#00bb00^' || BLUE_STAT=$BLUE_STAT'^c#aa0000^'
		BLUE_STAT=$BLUE_STAT'^r64,15,29,4^^d^'

		bluetoothctl info > /dev/null
		[ "$?" -eq "0" ] && BLUE_STAT=$BLUE_STAT'^c#00bb00^' || BLUE_STAT=$BLUE_STAT'^c#aa0000^'
		BLUE_STAT=$BLUE_STAT'^r98,15,4,4^^d^'
	fi
fi

echo '^f2^'$WIFI_GRAPH$BLUE_GRAPH'^f18^'$WIFI_STAT$BLUE_STAT'^f10^'$WIFI_RXTX'^f3^'
