#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

source .include/basic_widgets
source .include/small_text

color "$( xgetres dwm.normfgcolor )"
#draw_str 0 6 "awakate"

i=0
check_old_log_file() {
    [ -f "$1" ] && {
        draw_str 0 $((4 + ( 6 * i ))) "$2"
        #char_alert "$3" "$4"
        i=$((i+1))
    }
}

color "$( xgetres dwm.normfgcolor )"
check_old_log_file /home/castle/.cache/castle-dwm.log.old cwm warn C
check_old_log_file /home/castle/.cache/castle-dwm.log cdwm warn C
check_old_log_file /home/castle/.xsession-errors " xorg" error X

