#!/bin/sh
period=60
GLYPH='^c#8ea604^^r0,10,2,3^^r4,7,2,9^^r8,5,2,13^^r12,7,2,9^^r16,10,2,3^^f26^^d^' #\uf028 ' \uf026 for muted down here ¬
data="$(pactl list sinks)"
[[ "$( echo "$data" | grep "^[[:space:]]Mute:" | cut -d ' ' -f 2 )" == "yes" ]] && GLYPH='^c#ba1200^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f2^' && echo -e "#!/bin/dash\necho \" ^f2^$GLYPH XX^d^ \"" > /home/victor/repos/public/castat-modules/91_volume && exit 0
#[[ $( pulsemixer --get-mute ) -eq 1 ]] && GLYPH='^c#ba1200^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f4^^r0,10,2,3^^f2^' && echo -e ' '$GLYPH "XX^d^ " && exit 0

VOL=$( echo "$data" | grep '^[[:space:]]Volume:' | head -n 1 | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
#VOL=$( pulsemixer --get-volume | cut -d' ' -f1 )

#echo -e ' '$GLYPH$( echo $VOL )' '
echo -e "#!/bin/dash\necho \" $GLYPH$VOL \"" > /home/victor/repos/public/castat-modules/91_volume
